# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d68edf20e511c4c74a7485150039ad9898e2eb4024b4fc28649bb8ce6b6ce74060354488f69bb13f356a7ac82567a54deed7bf615b4d8978aab14974c1bdc9ca

test:
  secret_key_base: 6040865e95f55349dcade4c78c811be21549c95e9b90dead53cd2d90c808ca9dd49510d89771b0a92a95f3919ba3707995936e189047abd4b7f4d87cb3d970a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
